# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Build and Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v3
      - run: npm install -g yarn
      - run: yarn add nextjs
        working-directory: ./client
      - run: yarn build
        working-directory: ./client

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages  # 배포될 브랜치
          FOLDER: builds # 이 폴더에 있는 파일을 배포
          CLEAN: true 

